In [2]:
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import cross_validate
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split

In [3]:
data_path = '/Users/sola/Downloads/open/'
train = pd.read_csv(data_path + 'train.csv')
test = pd.read_csv(data_path + 'test.csv')
submission = pd.read_csv(data_path + 'sample_submission.csv')

In [4]:
train = train.fillna(0)
test = test.fillna(0)

In [5]:
# 모든 값이 0인 피처 지울거임..
wrong = []
for i in range(1,2876):
    ch = 'X_'+str(i)
    if train[ch].mean() == 0:
        wrong.append(ch)

print(wrong)
print(len(wrong))

['X_3', 'X_6', 'X_14', 'X_70', 'X_74', 'X_75', 'X_76', 'X_77', 'X_78', 'X_79', 'X_82', 'X_83', 'X_84', 'X_85', 'X_142', 'X_190', 'X_191', 'X_192', 'X_193', 'X_194', 'X_195', 'X_232', 'X_234', 'X_235', 'X_259', 'X_260', 'X_315', 'X_319', 'X_322', 'X_323', 'X_324', 'X_327', 'X_328', 'X_329', 'X_330', 'X_375', 'X_376', 'X_377', 'X_378', 'X_427', 'X_466', 'X_467', 'X_505', 'X_508', 'X_558', 'X_561', 'X_567', 'X_583', 'X_617', 'X_620', 'X_631', 'X_633', 'X_634', 'X_636', 'X_638', 'X_639', 'X_640', 'X_641', 'X_642', 'X_672', 'X_673', 'X_676', 'X_691', 'X_692', 'X_695', 'X_715', 'X_729', 'X_732', 'X_743', 'X_749', 'X_759', 'X_760', 'X_761', 'X_764', 'X_776', 'X_777', 'X_778', 'X_836', 'X_843', 'X_844', 'X_849', 'X_859', 'X_886', 'X_887', 'X_888', 'X_889', 'X_934', 'X_935', 'X_936', 'X_937', 'X_992', 'X_1020', 'X_1021', 'X_1022', 'X_1023', 'X_1024', 'X_1025', 'X_1070', 'X_1092', 'X_1119', 'X_1137', 'X_1146', 'X_1206', 'X_1216', 'X_1219', 'X_1248', 'X_1249', 'X_1250', 'X_1251', 'X_1252', 'X_125

In [6]:
train = train.drop(wrong, axis=1)
test = test.drop(wrong, axis=1)

train = train.drop(['TIMESTAMP','PRODUCT_ID'], axis=1)
test = test.drop(['TIMESTAMP','PRODUCT_ID'], axis=1)

In [7]:
train

Y_Class  Y_Quality     LINE PRODUCT_CODE   X_1   X_2   X_4   X_5   X_7  \
0          1   0.533433  T050304         A_31   0.0   0.0   0.0   0.0   0.0   
1          2   0.541819  T050307         A_31   0.0   0.0   0.0   0.0   0.0   
2          1   0.531267  T050304         A_31   0.0   0.0   0.0   0.0   0.0   
3          2   0.537325  T050307         A_31   0.0   0.0   0.0   0.0   0.0   
4          1   0.531590  T050304         A_31   0.0   0.0   0.0   0.0   0.0   
..       ...        ...      ...          ...   ...   ...   ...   ...   ...   
593        1   0.526546  T100306         T_31   2.0  95.0  45.0  10.0  50.0   
594        0   0.524022  T050304         A_31   0.0   0.0   0.0   0.0   0.0   
595        0   0.521289  T050304         A_31   0.0   0.0   0.0   0.0   0.0   
596        1   0.531375  T100304         O_31  40.0  94.0  45.0  11.0  45.0   
597        1   0.533702  T100306         O_31  21.0  87.0  45.0  10.0  61.0   

      X_8  ...  X_2862  X_2863      X_2864  X_2865  X_2866  X_2867  X_2868  \
0     0.0  ...   189.0   383.0  368.296296   353.0   39.34   40.89   32.56   
1     0.0  ...   185.6   383.0  367.735849   353.0   38.89   42.82   43.92   
2     0.0  ...   165.5   383.0  367.320755   353.0   39.19   36.65   42.47   
3     0.0  ...   165.8   384.0  369.188679   353.0   37.74   39.17   52.17   
4     0.0  ...   182.6   383.0  367.351852   352.0   38.70   41.89   46.93   
..    ...  ...     ...     ...         ...     ...     ...     ...     ...   
593  10.0  ...     0.0     0.0    0.000000     0.0    0.00    0.00    0.00   
594   0.0  ...   168.7   384.0  369.811321   353.0   49.47   53.07   50.89   
595   0.0  ...   156.6   383.0  367.018868   352.0    0.00    0.00    0.00   
596  10.0  ...     0.0     0.0    0.000000     0.0    0.00    0.00    0.00   
597  10.0  ...     0.0     0.0    0.000000     0.0    0.00    0.00    0.00   

     X_2869  X_2870  X_2871  
0     34.09   77.77     0.0  
1     35.34   72.55     0.0  
2     36.53   78.35     0.0  
3     30.58   71.78     0.0  
4     33.09   76.97     0.0  
..      ...     ...     ...  
593    0.00    0.00     0.0  
594   55.10   66.49     1.0  
595    0.00    0.00     1.0  
596    0.00    0.00     0.0  
597    0.00    0.00     0.0  

[598 rows x 2598 columns]

In [8]:
test

LINE PRODUCT_CODE  X_1   X_2   X_4   X_5   X_7   X_8   X_9  X_10  ...  \
0    T100306         T_31  2.0  94.0  45.0  10.0  51.0  10.0  52.0   2.0  ...   
1    T100304         T_31  2.0  93.0  45.0  11.0  45.0  10.0  31.0   2.0  ...   
2    T100304         T_31  2.0  95.0  45.0  11.0  45.0  10.0  31.0   2.0  ...   
3    T010305         A_31  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4    T010306         A_31  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
..       ...          ...  ...   ...   ...   ...   ...   ...   ...   ...  ...   
305  T100306         T_31  2.0  91.0  45.0  10.0  51.0  10.0  52.0   2.0  ...   
306  T100304         T_31  2.0  96.0  45.0  11.0  45.0  10.0  31.0   2.0  ...   
307  T100306         T_31  2.0  91.0  45.0  10.0  50.0  10.0  52.0   2.0  ...   
308  T100306         T_31  2.0  95.0  45.0  10.0  51.0  10.0  52.0   2.0  ...   
309  T100306         T_31  2.0  87.0  45.0  10.0  51.0  10.0  52.0   2.0  ...   

     X_2862  X_2863      X_2864  X_2865  X_2866  X_2867  X_2868  X_2869  \
0       0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
1       0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
2       0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
3     183.8   467.0  444.192308   423.0     0.0     0.0     0.0     0.0   
4     179.7   465.0  443.211539   423.0     0.0     0.0     0.0     0.0   
..      ...     ...         ...     ...     ...     ...     ...     ...   
305     0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
306     0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
307     0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
308     0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   
309     0.0     0.0    0.000000     0.0     0.0     0.0     0.0     0.0   

     X_2870  X_2871  
0       0.0     0.0  
1       0.0     0.0  
2       0.0     0.0  
3       0.0     0.0  
4       0.0     0.0  
..      ...     ...  
305     0.0     0.0  
306     0.0     0.0  
307     0.0     0.0  
308     0.0     0.0  
309     0.0     0.0  

[310 rows x 2596 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.ensemble import RandomForestClassifier

# 수치형으로 변환
qual_col = ['LINE', 'PRODUCT_CODE']

for i in qual_col:
    le = LabelEncoder()
    le = le.fit(train[i])
    train[i] = le.transform(train[i])

    for label in np.unique(test[i]):
        if label not in le.classes_:
            le.classes_ = np.append(le.classes_, label)
    test[i] = le.transform(test[i])
print('Done.')

Done.


In [10]:
train_x = train.drop(['Y_Class', 'Y_Quality'], axis=1)
y = train['Y_Class']

X_train, X_valid, y_train, y_valid = train_test_split(train_x, y, test_size=0.3, random_state=37)

In [24]:
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb


feat_labels = X_train.columns

rf = RandomForestClassifier(n_estimators = 1000, random_state = 0, n_jobs = -1)
# rf= lgb.LGBMClassifier(random_state=37)

rf.fit(X_train, y_train)
importances = rf.feature_importances_

# argsort : 리스트 인덱스의 정렬됐을 때의 인덱스 값 반환, [::-1] : 뒤집기
indices = np.argsort(importances)[::-1]


for i in range(X_train.shape[1]):
	print(feat_labels[indices[i]], importances[indices[i]])

#상위20개만...
a=[]
for i in range(100):
    a.append(feat_labels[indices[i]])
print(a)

X_1118 0.017271242607648854
X_1405 0.01665629136521816
X_1548 0.015383291023175562
X_1485 0.015368822370830877
X_1091 0.015259603935218323
X_1211 0.015125794328482956
X_1423 0.014994573148073164
X_718 0.014519865145480721
X_1500 0.014466255079901414
X_1339 0.014464481422528526
X_1774 0.014322997487606279
X_979 0.014262283990827029
X_1834 0.014213057831638475
X_240 0.014183563249745007
X_1428 0.014157821126726389
X_1617 0.01402362084882341
X_1198 0.013796140960755056
X_1473 0.013764008858550896
X_1083 0.013564046427720751
X_1475 0.013321541466649656
X_1636 0.013204879549014809
X_1077 0.01314478461622563
X_1849 0.012935785043911945
X_1414 0.012915779056259681
X_368 0.012817418684700769
X_1421 0.012471452410992994
X_73 0.012302905566187978
X_2846 0.012207599543572109
X_1665 0.011951844755341891
X_1329 0.011727505415940668
X_932 0.01141392264446386
X_367 0.011250859431393883
X_1161 0.011231592730816982
X_665 0.011192212180095083
X_318 0.011093391877900599
X_1056 0.010984600974371955
X_1049

In [26]:
from sklearn.metrics import confusion_matrix

train_x = train_x[a]
y = train['Y_Class']
test_x = test[a]

X_train, X_valid, y_train, y_valid = train_test_split(train_x, y, test_size=0.3, random_state=37)

rf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

prediction = rf.predict(X_valid)

# rf.score(X_valid, y_valid)
print(confusion_matrix(prediction, y_valid))
accuracy_score(prediction,y_valid)

[[  9   3   2]
 [ 12 121  16]
 [  0   7  10]]


0.7777777777777778

In [13]:
RF = RandomForestClassifier(n_jobs = -1 ,random_state=37)

In [27]:
# RF.fit(train_x, y)
# rf.
preds = rf.predict(test_x)

In [28]:
preds

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,

In [29]:
submit = pd.read_csv('/Users/sola/Downloads/open/sample_submission.csv')

In [30]:
submit['Y_Class'] = preds

In [31]:
submit.to_csv('/Users/sola/Downloads/open/baseline_submission11.csv', index=False)

피쳐중요도가 상위 20개만 골라서 돌려봄, 랜덤포레스트를 이용함
submission7
-> 정확도 0.5966049383 129위

피쳐중요도가 상위 500개만 골라서 돌려봄, 랜덤포레스트를 이용함
submission8
-> 정확도 0.5197085927
아니 왜내려가...? 검증데이터에서는 올라갔는데...

피쳐중요도가 상위 100개만 골라서 돌려봄, 랜덤포레스트를 이용함
submission9
-> 정확도 0.6189786059 109등!!
앙 기모리!!!!! 드디어 0.6대로 들어갔다~!!!!


피쳐중요도가 상위 80개만 골라서 돌려봄, 랜덤포레스트를 이용함
submission10
-> 정확도

피쳐중요도가 상위 100개만 골라서 돌려봄, 랜덤포레스트를 이용함, 근데 feature importance 구한
submission11
-> 정확도